version: '3.5'

services:
  integration:
    container_name: integration_service
    image: integration
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 443
    networks:
      - confluentkafka_shared-network

networks:
  confluentkafka_shared-network:
    external: true

