version: '3.5'

services:
  integration:
    image: integration
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8084:8084
      - 8080:8080
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=carp_integration
      - POSTGRES_DB=db_example
    ports:
      - 5432:5432

