version: '3.5'

services:
  integration:
    image: integration
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8084:8084
      - 8080:8080
    networks:
      - confluent-kafka_shared-network

networks:
  confluent-kafka_shared-network:
    external: true

