version: '3.5'

services:
  integration:
    image: integration
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8184:8184
      - 8180:8180
    networks:
      - confluent-kafka_shared-network

networks:
  confluent-kafka_shared-network:
    external: true

