version: '3.5'

services:
  integration:
    container_name: integration_service
    image: integration
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 443
    networks:
      - confluentkafka_shared-network
    volumes:
      - "/etc/letsencrypt/live/chaks.dk/privkey.pem:/etc/letsencrypt/live/chaks.dk/privkey.pem"
      - "/etc/letsencrypt/live/chaks.dk/fullchain.pem:/etc/letsencrypt/live/chaks.dk/fullchain.pem"

networks:
  confluentkafka_shared-network:
    external: true

